# Generated by Django 4.1.1 on 2022-09-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cek_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Car", new_name="viewer_cmd",),
    ]
