# Generated by Django 4.1.1 on 2022-09-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cek_app", "0002_rename_car_viewer_cmd"),
    ]

    operations = [
        migrations.DeleteModel(name="viewer_cmd",),
    ]
