# Generated by Django 4.1.1 on 2022-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cek_app", "0003_delete_viewer_cmd"),
    ]

    operations = [
        migrations.CreateModel(
            name="viewer_cmd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmd_input", models.TextField()),
                ("cmd_output", models.TextField()),
            ],
        ),
    ]
