# Generated by Django 4.1.1 on 2022-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cek_app", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="deneme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cmd_input", models.CharField(max_length=200)),
                ("cmd_output", models.CharField(max_length=200)),
            ],
        ),
    ]
